name: gui-dev
channels:
  - http://ssb.stsci.edu/astroconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_12
  - libgomp=15.2.0=he0feb66_12
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libsqlite=3.51.0=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_12
  - libuuid=2.41.2=he9a06e4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh145f28c_0
  - python=3.14.0=h32b2ec7_102_cp314
  - python_abi=3.14=8_cp314
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_ha0e22de_103
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - astropy==7.2.0
    - astropy-iers-data==0.2025.11.24.0.39.11
    - astroquery==0.4.11
    - beautifulsoup4==4.14.2
    - certifi==2025.11.12
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - contourpy==1.3.3
    - cryptography==46.0.3
    - cycler==0.12.1
    - fonttools==4.60.1
    - future==1.0.0
    - html5lib==1.1
    - idna==3.11
    - iso8601==2.1.0
    - jaraco-classes==3.4.0
    - jaraco-context==6.0.1
    - jaraco-functools==4.3.0
    - jeepney==0.9.0
    - keyring==25.7.0
    - kiwisolver==1.4.9
    - matplotlib==3.10.7
    - more-itertools==10.8.0
    - numpy==2.3.5
    - packaging==25.0
    - pandas==2.3.3
    - pillow==12.0.0
    - pycparser==2.23
    - pyerfa==2.0.1.5
    - pyparsing==3.2.5
    - pyqt5==5.15.11
    - pyqt5-qt5==5.15.18
    - pyqt5-sip==12.17.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyvo==1.8
    - pyyaml==6.0.3
    - regions==0.11
    - requests==2.32.5
    - scipy==1.16.3
    - secretstorage==3.5.0
    - serial==0.0.97
    - setuptools==80.9.0
    - sip==6.14.0
    - six==1.17.0
    - soupsieve==2.8
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - urllib3==2.5.0
    - webencodings==0.5.1
prefix: /home/black_neko/anaconda3/envs/gui-dev
